#!/usr/bin/env python3
from pathlib import Path
from datetime import date
import re, sys, json
try:
    import yaml
except ImportError:
    print('PyYAML is required: python3 -m pip install pyyaml', file=sys.stderr); raise
ROOT=Path(__file__).resolve().parents[1]
dev=yaml.safe_load((ROOT/'config/devices.yaml').read_text())['devices']
syscfg=yaml.safe_load((ROOT/'config/system.yaml').read_text())
t=yaml.safe_load((ROOT/'config/tariff_defaults.yaml').read_text())
ids=set()
for d in dev:
    if not re.fullmatch(r'[a-z0-9_]+',d['id']): raise SystemExit(f"Bad id: {d['id']}")
    if d['id'] in ids: raise SystemExit(f"Duplicate id: {d['id']}")
    ids.add(d['id'])
    if d['unit'] not in ('W','kW'): raise SystemExit(f"{d['id']}: unit must be W or kW")

def integ(name, uid, source, unit_prefix=None, round_n=6):
    lines=["  - platform: integration",f"    source: {source}",f"    name: {name}",f"    unique_id: {uid}"]
    if unit_prefix: lines.append(f"    unit_prefix: {unit_prefix}")
    lines += ["    unit_time: h","    method: left",f"    round: {round_n}"]
    return '\n'.join(lines)

def meter_block(key, source, cycle=None, cron=None):
    out=[f"  {key}:",f"    source: {source}"]
    if cycle: out.append(f"    cycle: {cycle}")
    if cron: out.append(f"    cron: '{cron}'")
    return out

start=date.fromisoformat(str(t['bill_cycle_start']))
bill_day=start.day
anchor=start.month
bill_months=[]
for i in range(4): bill_months.append(((anchor-1+3*i)%12)+1)
bill_months=sorted(set(bill_months))
bill_cron=f"0 0 {bill_day} {','.join(map(str,bill_months))} *"

p=['# AUTO-GENERATED by tools/generate.py — edit config/*.yaml, not this file.','# v0.5 accounting engine: live TOU cost integration preserves historical rates.','']
p += ['input_number:']
nums=[('utility_peak_rate','Utility Peak Rate',0,2,0.000001,'AUD/kWh',t['peak_rate']),('utility_shoulder_rate','Utility Shoulder Rate',0,2,0.000001,'AUD/kWh',t['shoulder_rate']),('utility_offpeak_rate','Utility Off Peak Rate',0,2,0.000001,'AUD/kWh',t['offpeak_rate']),('utility_supply_daily','Utility Daily Supply Charge',0,10,0.000001,'AUD/day',t['supply_daily']),('utility_fit_tier1','Utility FIT Tier 1',0,1,0.000001,'AUD/kWh',t['fit_tier1']),('utility_fit_tier2','Utility FIT Tier 2',0,1,0.000001,'AUD/kWh',t['fit_tier2']),('utility_fit_threshold','Utility FIT Tier 1 Daily Limit',0,100,0.1,'kWh',t['fit_threshold_kwh_day'])]
for i,n,mi,ma,st,u,v in nums:
    p += [f'  {i}:',f'    name: {n}',f'    min: {mi}',f'    max: {ma}',f'    step: {st}','    mode: box',f'    unit_of_measurement: {u}',f'    initial: {v}']
p += ['','input_text:','  utility_plan_name:','    name: Utility Plan Name',f"    initial: '{t['plan_name']}'",'  utility_bill_cycle_start:','    name: Utility Bill Cycle Start',f"    initial: '{t['bill_cycle_start']}'",'','template:','  - sensor:']
p += ['      - name: Utility Active Tariff','        unique_id: utility_active_tariff','        state: >-',"          {% set m = now().hour * 60 + now().minute %}",f"          {{% if {t['peak_1_start']} <= m < {t['peak_1_end']} or {t['peak_2_start']} <= m < {t['peak_2_end']} %}}peak",f"          {{% elif {t['shoulder_start']} <= m < {t['shoulder_end']} %}}shoulder",'          {% else %}offpeak{% endif %}']
p += ['      - name: Utility Active Import Rate','        unique_id: utility_active_import_rate','        unit_of_measurement: AUD/kWh','        state_class: measurement','        state: >-',"          {% set x = states('sensor.utility_active_tariff') %}","          {% if x == 'peak' %}{{ states('input_number.utility_peak_rate') }}","          {% elif x == 'shoulder' %}{{ states('input_number.utility_shoulder_rate') }}","          {% else %}{{ states('input_number.utility_offpeak_rate') }}{% endif %}"]
# Power accounting sensors
expr=[]
for d in dev:
    factor='1000' if d['unit']=='kW' else '1'; expr.append(f"(states('{d['source']}')|float(0) * {factor})")
tracked_expr=' + '.join(expr) if expr else '0'
p += ['      - name: Utility Tracked Power','        unique_id: utility_tracked_power','        unit_of_measurement: W','        device_class: power','        state_class: measurement','        state: >-',f'          {{{{ ({tracked_expr}) | round(1) }}}}']
p += ['      - name: Utility Untracked Power','        unique_id: utility_untracked_power','        unit_of_measurement: W','        device_class: power','        state_class: measurement','        state: >-',f"          {{% set h = states('{syscfg['house_power']}')|float(0) %}}","          {% set tr = states('sensor.utility_tracked_power')|float(0) %}",'          {{ [h-tr,0]|max|round(1) }}']
# Instantaneous cost-flow sensors in AUD/h. Integrating these is the historical cost ledger.
def costflow(name,uid,power_entity,power_unit='W',rate_entity="sensor.utility_active_import_rate"):
    div='1000' if power_unit=='W' else '1'
    return ['      - name: '+name,'        unique_id: '+uid,'        unit_of_measurement: AUD/h','        state_class: measurement','        state: >-',f"          {{{{ ((states('{power_entity}')|float(0)) / {div} * (states('{rate_entity}')|float(0))) | round(6) }}}}"]
p += costflow('Utility Grid Import Cost Flow','utility_grid_import_cost_flow',syscfg['grid_import_power'])
p += ['      - name: Utility Supply Cost Flow','        unique_id: utility_supply_cost_flow','        unit_of_measurement: AUD/h','        state_class: measurement','        state: >-',"          {{ (states('input_number.utility_supply_daily')|float(0) / 24) | round(6) }}"]
for d in dev: p += costflow(f"Utility {d['name']} Cost Flow",f"utility_{d['id']}_cost_flow",d['source'],d['unit'])
p += costflow('Utility Untracked Cost Flow','utility_untracked_cost_flow','sensor.utility_untracked_power')
# FIT flow: daily export meter decides current tier; exported power earns the corresponding rate.
p += ['      - name: Utility Active FIT Rate','        unique_id: utility_active_fit_rate','        unit_of_measurement: AUD/kWh','        state_class: measurement','        state: >-',"          {% set e = states('sensor.utility_grid_export_energy_daily')|float(0) %}","          {% set lim = states('input_number.utility_fit_threshold')|float(0) %}","          {{ states('input_number.utility_fit_tier1') if e < lim else states('input_number.utility_fit_tier2') }}"]
p += costflow('Utility Solar Credit Flow','utility_solar_credit_flow',syscfg['grid_export_power'],'W','sensor.utility_active_fit_rate')

p += ['','sensor:']
p.append(integ('Utility Grid Import Energy','utility_grid_import_energy',syscfg['grid_import_power'],'k',5))
p.append(integ('Utility Grid Export Energy','utility_grid_export_energy',syscfg['grid_export_power'],'k',5))
for d in dev: p.append(integ(f"Utility {d['name']} Energy",f"utility_{d['id']}_energy",d['source'],'k' if d['unit']=='W' else None,5))
# Integrate cost flows. No prefix: AUD/h * h => AUD.
for name,uid,source in [('Utility Grid Import Cost','utility_grid_import_cost','sensor.utility_grid_import_cost_flow'),('Utility Supply Cost','utility_supply_cost','sensor.utility_supply_cost_flow'),('Utility Solar Credit Cost','utility_solar_credit_cost','sensor.utility_solar_credit_flow'),('Utility Untracked Cost','utility_untracked_cost','sensor.utility_untracked_cost_flow')]:
    p.append(integ(name,uid,source,None,6))
for d in dev: p.append(integ(f"Utility {d['name']} Cost",f"utility_{d['id']}_cost",f"sensor.utility_{d['id']}_cost_flow",None,6))

p += ['','utility_meter:']
# Energy periods
for d in [{'id':'grid_import'},{'id':'grid_export'}]+dev:
    src=f"sensor.utility_{d['id']}_energy"
    for suffix,cycle in [('daily','daily'),('monthly','monthly'),('yearly','yearly')]: p += meter_block(f"utility_{d['id']}_energy_{suffix}",src,cycle=cycle)
    p += meter_block(f"utility_{d['id']}_energy_bill",src,cron=bill_cron)
# Cost periods, including bill cycle
cost_ids=['grid_import','supply','solar_credit','untracked']+[d['id'] for d in dev]
for cid in cost_ids:
    src=f"sensor.utility_{cid}_cost"
    for suffix,cycle in [('daily','daily'),('monthly','monthly'),('yearly','yearly')]: p += meter_block(f"utility_{cid}_cost_{suffix}",src,cycle=cycle)
    p += meter_block(f"utility_{cid}_cost_bill",src,cron=bill_cron)
# Net bill sensors per period and tracked totals.
p += ['','template:','  - sensor:']
for suffix,label in [('daily','Today'),('monthly','Month'),('bill','Bill Cycle'),('yearly','Year')]:
    p += [f'      - name: Utility Net Cost {label}',f'        unique_id: utility_net_cost_{suffix}','        unit_of_measurement: AUD','        state_class: measurement','        state: >-',f"          {{{{ ((states('sensor.utility_grid_import_cost_{suffix}')|float(0)) + (states('sensor.utility_supply_cost_{suffix}')|float(0)) - (states('sensor.utility_solar_credit_cost_{suffix}')|float(0))) | round(2) }}}}"]
    devsum=' + '.join([f"(states('sensor.utility_{d['id']}_cost_{suffix}')|float(0))" for d in dev]) or '0'
    p += [f'      - name: Utility Tracked Cost {label}',f'        unique_id: utility_tracked_cost_{suffix}','        unit_of_measurement: AUD','        state_class: measurement','        state: >-',f'          {{{{ ({devsum}) | round(2) }}}}']

(ROOT/'packages/utility_cost.yaml').write_text('\n'.join(p)+'\n')
registry={'bill_cycle_cron':bill_cron,'devices':[]}
for d in dev:
    x={**d,'energy_entity':f"sensor.utility_{d['id']}_energy",'cost_entity':f"sensor.utility_{d['id']}_cost"}
    for period in ('daily','monthly','bill','yearly'):
        x[f'{period}_energy_entity']=f"sensor.utility_{d['id']}_energy_{period}"
        x[f'{period}_cost_entity']=f"sensor.utility_{d['id']}_cost_{period}"
    registry['devices'].append(x)
(ROOT/'www/utility-cost-devices.js').write_text('window.UTILITY_COST_DEVICES = '+json.dumps(registry,separators=(',',':'))+';\n')
print(f'Generated v0.5 package for {len(dev)} tracked devices. Bill reset cron: {bill_cron}')
